[package]
name = "volctl"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3"
gdk = { version = "0.9", package = "gdk4", features = ["v4_16"] }
gdk-x11 = { version = "0.9", package = "gdk4-x11", features = ["v4_16"] }
glib = "0.20"
gtk = { version = "0.9", package = "gtk4", features = ["v4_16"] }
gtk-layer-shell = { version = "0.4.0", package = "gtk4-layer-shell" }
ksni = "0.2"
libpulse = { version = "2.28", package = "libpulse-binding" }
slice_as_array = "1.1"
x11rb = "0.13"
