[package]
name = "wayland-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
gdk = { version = "0.9.2", package = "gdk4", features = ["v4_16"] }
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_16"] }
gtk4-layer-shell = "0.4.0"
ksni = "0.2.2"
libappindicator = "0.9"
